# Generated by Django 3.0.8 on 2020-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PEN', 'PENDING'), ('PAI', 'PAID')], default='PENDING', max_length=3),
        ),
    ]
